### ISSUE TITLE
Edit page crashes.

### ISSUE THREAD

**Issue by modreoci** [refinerycms-contrib/refinerycms-multisites#1]
Trying to edit page return this message:

NoMethodError in Refinery::Admin::Pages#edit
(vis image)

![screenshot-lvh me 3000 2016-03-28 21-07-39](https://cloud.githubusercontent.com/assets/10616435/14087289/732f0674-f529-11e5-8a20-d4b816f7ae6b.png)

```
Started GET "/refinery/pages/home/edit?switch_locale=en" for 127.0.0.1 at 2016-03-28 20:58:09 +0200
Processing by Refinery::Admin::PagesController#edit as HTML
  Parameters: {"switch_locale"=>"en", "path"=>"home", "locale"=>:sk}
  Refinery::Authentication::Devise::User Load (0.2ms)  SELECT  "refinery_authentication_devise_users".* FROM "refinery_authentication_devise_users" WHERE "refinery_authentication_devise_users"."id" = ?  ORDER BY "refinery_authentication_devise_users"."id" ASC LIMIT 1  [["id", 2]]
  Refinery::Page Load (0.8ms)  SELECT  "refinery_pages".* FROM "refinery_pages" INNER JOIN "refinery_page_translations" ON "refinery_page_translations"."refinery_page_id" = "refinery_pages"."id" WHERE "refinery_pages"."parent_id" IS NULL AND "refinery_page_translations"."locale" IN ('sk', 'en') AND "refinery_page_translations"."slug" = 'home'  ORDER BY "refinery_pages"."id" ASC LIMIT 1
  Refinery::Authentication::Devise::Role Load (0.2ms)  SELECT "refinery_authentication_devise_roles".* FROM "refinery_authentication_devise_roles" INNER JOIN "refinery_authentication_devise_roles_users" ON "refinery_authentication_devise_roles"."id" = "refinery_authentication_devise_roles_users"."role_id" WHERE "refinery_authentication_devise_roles_users"."user_id" = ?  [["user_id", 2]]
  Refinery::Authentication::Devise::UserPlugin Load (0.2ms)  SELECT "refinery_authentication_devise_user_plugins".* FROM "refinery_authentication_devise_user_plugins" WHERE "refinery_authentication_devise_user_plugins"."user_id" = ?  ORDER BY position ASC  [["user_id", 2]]
  Refinery::Page::Translation Load (0.2ms)  SELECT "refinery_page_translations".* FROM "refinery_page_translations" WHERE "refinery_page_translations"."refinery_page_id" = ?  [["refinery_page_id", 1]]
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/core/app/views/refinery/admin/_error_messages.html.erb (0.1ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/core/app/views/refinery/admin/_locale_picker.html.erb (6.2ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/_form_fields_after_title.html.erb (1.0ms)
  Refinery::PagePart Load (0.3ms)  SELECT "refinery_page_parts".* FROM "refinery_page_parts" WHERE "refinery_page_parts"."refinery_page_id" = ?  ORDER BY position ASC  [["refinery_page_id", 1]]
  Refinery::PagePart::Translation Load (0.5ms)  SELECT "refinery_page_part_translations".* FROM "refinery_page_part_translations" WHERE "refinery_page_part_translations"."refinery_page_part_id" IN (1, 2)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/_page_part_field.html.erb (3.5ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/_page_part_field.html.erb (2.2ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/_form_page_parts.html.erb (44.4ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/core/app/views/refinery/admin/_form_advanced_options_menu.html.erb (2.2ms)
  Refinery::Page Load (0.6ms)  SELECT "refinery_pages".* FROM "refinery_pages" WHERE "refinery_pages"."parent_id" IS NULL  ORDER BY "refinery_pages"."lft"
  Refinery::Page Load (0.7ms)  SELECT "refinery_pages".* FROM "refinery_pages" WHERE ("refinery_pages"."lft" >= 1) AND ("refinery_pages"."lft" < 4)  ORDER BY "refinery_pages"."lft"
  Refinery::Page Load (0.5ms)  SELECT "refinery_pages".* FROM "refinery_pages" WHERE ("refinery_pages"."lft" >= 5) AND ("refinery_pages"."lft" < 6)  ORDER BY "refinery_pages"."lft"
  Refinery::Page::Translation Load (0.4ms)  SELECT "refinery_page_translations".* FROM "refinery_page_translations" WHERE "refinery_page_translations"."refinery_page_id" IN (3)
  Refinery::Multisites::Account Load (1.5ms)  SELECT  "refinery_multisites_accounts".* FROM "refinery_multisites_accounts" WHERE "refinery_multisites_accounts"."subdomain" = ? LIMIT 1  [["subdomain", ""]]
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/_form_advanced_options.html.erb (59.7ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/_form.html.erb (184.9ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/edit.html.erb within layouts/refinery/admin (190.1ms)
Completed 500 Internal Server Error in 220ms (ActiveRecord: 6.2ms)

ActionView::Template::Error (undefined method `subdomain' for nil:NilClass):
    25:         <%= f.label :view_template, t('.view_template') %>
    26:         <%= refinery_help_tag t('.view_template_help') %>
    27:       </span>
    28:       <%= f.select :view_template, valid_view_templates.map { |t| [t.titleize, t] },
    29:                    template_options(:view_template, @page) %>
    30:     </div>
    31: 
  /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-multisites-14c6ae6ff780/app/decorators/controllers/refinery/admin/pages_controller_decorator.rb:12:in `account_view_templates_pattern'
  /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-multisites-14c6ae6ff780/app/decorators/controllers/refinery/admin/pages_controller_decorator.rb:24:in `valid_view_templates'
  actionpack (4.2.5) lib/abstract_controller/helpers.rb:67:in `valid_view_templates'
  /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/_form_advanced_options.html.erb:28:in `__home_at__rvm_gems_ruby_______rcmsmulti_bundler_gems_refinerycms_dd___f_f___d_pages_app_views_refinery_admin_pages__form_advanced_options_html_erb__668357240__660377298'
  actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.5) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/_form.html.erb:19:in `block in __home_at__rvm_gems_ruby_______rcmsmulti_bundler_gems_refinerycms_dd___f_f___d_pages_app_views_refinery_admin_pages__form_html_erb___234702907__653897428'
  actionview (4.2.5) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.5) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.5) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.5) lib/action_view/helpers/form_helper.rb:444:in `form_for'
  /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/_form.html.erb:1:in `__home_at__rvm_gems_ruby_______rcmsmulti_bundler_gems_refinerycms_dd___f_f___d_pages_app_views_refinery_admin_pages__form_html_erb___234702907__653897428'
  actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.5) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/app/views/refinery/admin/pages/edit.html.erb:1:in `__home_at__rvm_gems_ruby_______rcmsmulti_bundler_gems_refinerycms_dd___f_f___d_pages_app_views_refinery_admin_pages_edit_html_erb___632909227__667277608'
  actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.5) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.5) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/at/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:43:in `render'
  /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/bundler/gems/refinerycms-dd547f8f217d/pages/lib/refinery/pages/instance_methods.rb:21:in `render'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.5) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
  dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
  apartment (1.0.2) lib/apartment/reloader.rb:18:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (3.2.0) lib/puma/configuration.rb:227:in `call'
  puma (3.2.0) lib/puma/server.rb:561:in `handle_request'
  puma (3.2.0) lib/puma/server.rb:406:in `process_client'
  puma (3.2.0) lib/puma/server.rb:271:in `block in run'
  puma (3.2.0) lib/puma/thread_pool.rb:111:in `block in spawn_thread'


  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_source.erb (28.8ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (10.9ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (3.4ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/actionpack-4.2.5/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (94.1ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (1.1ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.8ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.7ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.8ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (46.9ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.7ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.9ms)
  Rendered /home/at/.rvm/gems/ruby-2.3.0@rcmsmulti/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (93.5ms)
```

Gemfile

``` ruby
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'
gem 'devise-i18n'
gem 'foundation-rails', '5.5.3.2'
gem 'refinerycms-multisites', github: 'bricesanchez/refinerycms-multisites', branch: 'master'
# Use sqlite3 as the database for Active Record
group :development, :test do
  gem 'sqlite3'
end
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

group :production do
  gem 'pg'
  gem 'rails_12factor'
  gem 'puma'
end
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end


gem 'refinerycms', git: 'https://github.com/refinery/refinerycms', branch: 'master'

gem 'quiet_assets', group: :development

# Add support for searching inside Refinery's admin interface.
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.0']

# Add support for Refinery's custom fork of the visual editor WYMeditor.
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']

# The default authentication adapter
gem 'refinerycms-authentication-devise', '~> 1.0'
ruby "2.3.0"

```

**Comment by modreoci** [comment]
Sorry I forgot to set
config.single_tenant_mode = false

**Comment by bricesanchez** [comment]
Sorry, this is a working progress it needs more work.
